const SUCCESSFUL = 'SUCCESSFUL';
const CREATED = 'CREATED';
const NOT_FOUND = 'NOT_FOUND';
const CONFLICT = 'CONFLICT';
const INVALID_VALUE = 'INVALID_VALUE';

module.exports = {
  SUCCESSFUL,
  CREATED,
  NOT_FOUND,
  CONFLICT,
  INVALID_VALUE,
};