const httpStatusName = {
  SUCCESSFUL: 'SUCCESSFUL',
  CREATED: 'CREATED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INVALID_VALUE: 'INVALID_VALUE',
  BAD_REQUEST: 'BAD_REQUEST',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
};

module.exports = httpStatusName;